### ISSUE TITLE
Create the Movies List Page

### ISSUE THREAD

**Issue by Keen91** [Recoded-BPRM-Turkey-FEW-2022/movie-project-h-k#7]

**Comment by Keen91** [comment]
- [ ] #7 - Grid with the 3 columns for desktop size
- [ ] #7 - Grid with the 2 columns for tablet size
- [ ] #7 - Grid with the 1 column for mobile size
- [ ] #7 - Rating, genres and description
