### ISSUE TITLE
Create the Single Movie Page

### ISSUE THREAD

**Issue by Keen91** [Recoded-BPRM-Turkey-FEW-2022/movie-project-h-k#8]

**Comment by Keen91** [comment]
- [ ] #8 - Main 5 actors in credits
- [ ] #8 - Movie language
- [ ] #8 - Related movie section with 5 related movies
- [ ] #8 - Trailer section (YouTube)
- [ ] #8 - Movie Production Company Info
- [ ] #8 - Director Name
- [ ] #8 - Movie rating with voting
- [ ] #8 - Clicking on actor takes us to the actor page
- [ ] #8 - Fixing duplication issues
